### ISSUE TITLE
[Regression] Validator claims "'amp-ad' was found on this page, but is unused" although it is being used

### ISSUE THREAD

**Issue by steffenweber** [ampproject/amphtml#10002]
## What's the issue?

Since today, the AMP validator logs the following warning when loading the 'amp-ad' extension *even if 'amp-ad' tags actually exist in the HTML code*:

```
The extension 'amp-ad' was found on this page, but is unused (no 'amp-ad' tag seen). This may become an error in the future.
```

## How do we reproduce the issue?

1. Open https://www.computerbase.de/2017-06/dell-ultrasharp-u3818dw/?amp=1#development=1
2. Have a look at the developer tools console

Alternatively install `amphtml-validator` and run:

1. `amphtml-validator "https://www.computerbase.de/2017-06/dell-ultrasharp-u3818dw/?amp=1"`

## What browsers are affected?

This is a validator issue, so I guess this does not apply. I've tested in Chrome 59, in Firefox 54 and with the amphtml-validator cli.

## Which AMP version is affected?

Version 1496877433269. We've first noticed this issue at 3am CEST today. It did not exist before midnight. (We automatically check a sample of our AMPs every three hours.)

**Comment by honeybadgerdontcare** [comment]
This was introduced in PR #9742. See new [test .out file](https://github.com/ampproject/amphtml/pull/9742/files#diff-75f921f16c86f0e6561f0e729b7bc902) for amp-ad.

**Comment by Gregable** [comment]
This was missed because it is only a warning, but I'm rolling back the javascript release for not until this is solved.

**Comment by Gregable** [comment]
This is now fixed.

**Comment by steffenweber** [comment]
Thank you! :)

**Comment by SGr33n** [comment]
Hi, does this also affects the Google Search Console validator? I'm still facing this warning since 3 days ago.

**Comment by joshcp** [comment]
I presume related errors in Search Console will clear out as pages are re-indexed. Is that correct, @Gregable?

**Comment by SGr33n** [comment]
Sure, but they're still increasing, and "Last detected:	6/22/17".

**Comment by Gregable** [comment]
That is correct, the Search Console errors will eventually clear out.
