### ISSUE TITLE
problem with amp-sidebar

### ISSUE THREAD

**Issue by dldl53** [ampproject/amphtml#11708]
Hello, 

I have built an AMP page with the scrolling menu working Ok when I check it via the search console amp test and preview . However the menu won't work if I access to the page via google search engine through a mobile device:
https://www.google.com/amp/s/www.amp.datingland.fr/amoureux-by-meetic.html
When clicking on the menu button,  the side bar with menu categories won't display on the right side of the page as it does when I check the page on itself:

http://amp.datingland.fr/amoureux-by-meetic.html

![image](https://user-images.githubusercontent.com/32857976/31643980-cb867dc8-b2f3-11e7-9277-0affa51d0f47.png)

**Comment by aghassemi** [comment]
@dldl53 this should be resolved now, could you please verify?

**Comment by dldl53** [comment]
Thank you for your reply. No, still not working but I assume the problem is in my code.

**Comment by dldl53** [comment]
If you click on first link on my message from mobile device you will see that the side bar menu is not working.

**Comment by aghassemi** [comment]
@dldl53 what device are you using? It works for me on Android/Chrome.

**Comment by dldl53** [comment]
i have tried on iphone6 with chrome and safari, the menu won't open somehow on this link:
https://www.google.com/amp/s/www.amp.datingland.fr/amoureux-by-meetic.html

**Comment by aghassemi** [comment]
@dldl53 I can repro now. It behaves and looks completely different on iOS. Looking into what's causing it.

**Comment by aghassemi** [comment]
@dvoytenko @jridgewell 
In iOS embed case, sidebar is moved to the fixed layer which is another `body` but the toggle stays inside the `html` wrapper we ad. This means `getElementById('sidebar')` runs in a different root than where the actual `<sidebar id=sidebar>` is causing element not found errors.

See
![toggle](https://user-images.githubusercontent.com/2099009/31735736-acbd0a6a-b3f7-11e7-9588-378ee9b3a97a.gif)

**Comment by jridgewell** [comment]
It's because there are two elements with an id of `sidebar`. When we reparent, it moves the `amp-sidebar[id="sidebar"]` to be later in the document. Because of that, the `aside[id="sidebar"]` is now the first element with that id in the page, and `#getElementById` now returns the aside.

**Comment by aghassemi** [comment]
@jridgewell Good find. Thanks for investigating.

**Comment by dldl53** [comment]
@dvoytenko @jridgewell
I see, thank you both for your time
