### ISSUE TITLE
Last item in bookend isn't aligned with other items

### ISSUE THREAD

**Issue by bpaduch** [ampproject/amphtml#12250]
On the bookend page for an AMP story, the last item for related-articles doesn't align with the other items. This occurs when viewport width is < 640px.

Screenshot:
![amp-story-bookend-last-item](https://user-images.githubusercontent.com/1012254/33391567-7c035e52-d507-11e7-99d6-804500677869.png)

It looks like whatever is in `.i-amphtml-story-bookend-article-set:after` is shifting the content left.

Live preview example (has just two items but last is shifted): https://bap-amp-001.appspot.com/

**Comment by alanorozco** [comment]
Fixed by #12415.

**Comment by bpaduch** [comment]
@alanorozco  - I think this *was* fixed but has since been reverted.  I can still reproduce the issue (on mobile device and mobile emulator).

**Comment by bpaduch** [comment]
Closing again ... appears to be fix .. again. :)
