### ISSUE TITLE
Error: Cannot read property 'resolve' of undefined

### ISSUE THREAD

**Issue by zhouyx** [ampproject/amphtml#16218]
High frequency error. 20k+/hour reported @ 1% canary. The error tracking doesn't make much sense to me : ( Can someone take a look. 

Error: Cannot read property 'resolve' of undefined
    at getRealChildNodes (https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/base-element.js:769:2)
    at https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/element-stub.js:44:2
    at https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/service/resources-impl.js:990:28
    at mutate (https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/service/resources-impl.js:1020:14)
    at https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/service/resources-impl.js:555:30
    at https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/service/resources-impl.js:1200:20
    at undefined (https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/service/history-impl.js:591:22)
    at onVisibilityChanged (https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/service/resources-impl.js:251:4)
    at https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/service/history-impl.js:646:23
    at https://raw.githubusercontent.com/ampproject/amphtml/1529458017017/src/service/url-replacements-impl.js:690:39

go/amp-error/CLCt-5Cr_MnxYw
go/amp-error/CNODn--Qs-rZzgE

**Comment by choumx** [comment]
https://github.com/ampproject/amphtml/blob/f8da39e8f38774222491cf262ecb9d171dfdf52f/src/service/resource.js#L697-L703

Looks like `this.withViewportDeferreds_[viewportInt]` is undefined.

**Comment by jridgewell** [comment]
It's the typecast: `parseInt(keys[i], 10)`. Must be getting a float somewhere.

**Comment by choumx** [comment]
#15989 added this code a few days ago and might be the culprit. 

https://github.com/ampproject/amphtml/commit/a689b65162f27fc419fad66b192a5f2d70070aa0#diff-9379e12fba31cf69d032da3c00ba0c8eR700

/cc @keithwrightbos

**Comment by zhouyx** [comment]
@jridgewell I tried with `parseInt(1.25, 10)` on chrome , and that works for me.

**Comment by jridgewell** [comment]
Yup, here the key is `"1.25"`. After the parseInt, we try to do `obj[1].resolve()`, but the key was `1.25`.

**Comment by zhouyx** [comment]
no the returned value from `parseInt(1.25, 10)` is 1, I think it's `obj[1]` that doesn't exist.

**Comment by jridgewell** [comment]
That’s what I just said. 😜

**Comment by choumx** [comment]
Fixed by #16238.

**Comment by zhouyx** [comment]
I am still seeing this error after cherrypick. The error rate has decreased a lot though.

go/amp-error/CNODn--Qs-rZzgE

**Comment by jridgewell** [comment]
Getting roughly 50 per hour, dropping to P1. Have a fix in the works.
