### ISSUE TITLE
Development mode: MANDATORY_TAG_MISSING amphtml engine v1.js script

### ISSUE THREAD

**Issue by gustavopaes** [ampproject/amphtml#174]
What means this development mode message?
MANDATORY_TAG_MISSING amphtml engine v1.js script

Tks

**Comment by erwinmombay** [comment]
i believe this has been fixed/implemented?

**Comment by powdercloud** [comment]
Yes I believe the issues mentioned herein are fixed, including warnings are sent to console.warn if it exists. If anyone remains unhappy, please say hi again.

**Comment by erwinmombay** [comment]
like what @powdercloud just say hi again if you feel anything has not been resolved. closing for now.

**Comment by ameshkin** [comment]
guys,

I'm using the wordpress plugin and I'm still getting that error.

I'm also getting this but can't figure out where to disable dev mode.

DEV_MODE_ENABLED development - please remove for prod

**Comment by rudygalfi** [comment]
Do you have this in your generated markup?

```<script async src="https://cdn.ampproject.org/v0.js" development></script>```

That should be what's causing this error. You might need to follow up in https://github.com/Automattic/amp-wp if you think this mode is being enabled incorrectly. It looks like there is some flag to toggle it but I'm not sure how you do that with the plug-in.

**Comment by ameshkin** [comment]
Yes, I do have this line in my code.

Im debating whether or not I should update the plugin myself, or wait until the developers do it.

	<script src="https://cdn.ampproject.org/v0.js" async development></script>

**Comment by dvoytenko** [comment]
It should definitely be removed. Are you seeing this produced by WordPress plugin? If so, Rudy, do you think we could ask them to remove it sooner?

**Comment by rudygalfi** [comment]
I submitted https://github.com/Automattic/amp-wp/issues/86

**Comment by dvoytenko** [comment]
This has been fixed on WordPress side. Thus I'm closing this issue.

**Comment by ameshkin** [comment]
I downloaded this plugin again, but there does not seem to be any difference :(
Perhaps wordpress has the zip file cached?
But thanks for fixing this outside of wordpress and responding so quickly.

https://wordpress.org/plugins/amp/

**Comment by ameshkin** [comment]
Guys,

Is there a way I can tell AMP to just ignore an image?  I have this small twitter image, which I tried changing to an SVG.

If you don't give an image a width or a height, it's surrounded by a red circle.  So I did that as well.

But no matter what, the google amp plugin wants every image to be full size.  Is there something I can do to just get it to not show up on the amp page?

http://tp.ameshkin.devprogress.org/justice/2015/11/24/3725294/white-supremacists-black-lives-matter-minneapolis/?amp=1

**Comment by dvoytenko** [comment]
RE:development attribute. From what I can tell from https://github.com/Automattic/amp-wp/commit/584883fa1f283af005716bb8ff56d40e5423a0e7 you may be able to disable it via some sort of `AMP_DEV_MODE` variable?

**Comment by ameshkin** [comment]
Thanks, setting that constant to false does work now where it did not before.

Thank you

define('AMP_DEV_MODE',0);

If someone can help with the image/svg issue, it would be appreciated.  We should probably really be using font awesome or a symbol, but that would require too much code for just one little thing.

**Comment by rudygalfi** [comment]
@ameshkin Thanks for raising these issues. It's super-important that they get resolved. I think  Automattic/amp-wp would be a better place to bring these up as it related to behavior of the WordPress plug-in rather than the AMP format itself. Please try submitting a new issue at https://github.com/Automattic/amp-wp/issues/new

**Comment by dvoytenko** [comment]
@ameshkin not sure I understand about image. I'm looking at your doc and it validates correctly and I don't see red circles around image. Could you please confirm or send me a screenshot?

**Comment by dvoytenko** [comment]
Also, if you don't mind - could you please open a new issue for this?

**Comment by ameshkin** [comment]
I will create a new issue.  But the red box goes away, after I give the twitter image a width and a height.

But it still wants to make everything large.

Then I turned it from a png to an svg, thinking perhaps it would treat it differently.

It does treat it differently, ha ha, but still wants to apply css to the svg and make it larger than it should be.

It would be nice if we could just add a class to images and amp would be smart enough to just ignore.

**Comment by ameshkin** [comment]
Thank you guys for all your help. We hope to start using amp on think progress as soon as possible.
