### ISSUE TITLE
Error in required structured data element

### ISSUE THREAD

**Issue by mikedidthis** [ampproject/amphtml#18227]
![mosaic capture 2018-09-20 at 17 43 57](https://user-images.githubusercontent.com/910412/45833600-f3087b80-bcfc-11e8-9ae5-92fc735de682.png)
![mosaic capture 2018-09-20 at 17 43 52](https://user-images.githubusercontent.com/910412/45833617-f7cd2f80-bcfc-11e8-8066-1f7165ab949b.png)

## What's the issue?

Google Search Console is reporting the following error:

> Error in required structured data element

However Structured Data Testing Tool validates the data.

## Example URLs:

1. https://www.care.com/c/stories/12020/10-scenic-cider-mills-and-apple-orchards-in-metro-detroit-michigan/amp/
2. https://www.care.com/c/stories/5766/caregiver-support-groups/amp/
3. https://www.care.com/c/stories/10235/housekeeper-contracts-issues-to-consider-before-you-hire/amp/
4. https://www.care.com/c/stories/10250/pet-care-options/amp/

## How do we reproduce the issue?

1. Open example URL in Google Search Console
2. View Issues: "Error in required structured data element > AMP version has invalid structured data"
3. Open example URL in Structured Data Testing Tool
4. View Results:  "0 ERRORS, 0 WARNINGS"

I have search extensively for some sort of clue to this error but I have found nothing. Any help would be appreciated!

**Comment by OptimumGraph** [comment]
Hi @mikedidthis 
This is a Structured Data error. Although you have 0 Errors and 0 Warnings in the Structured Data Testing Tool, there is also no green preview button.
For your example url [https://www.care.com/c/stories/10250/pet-care-options/amp/](url) if you change your structure data to this:

`<script type="application/ld+json">
[{"@context":"http://schema.org","@type":"BreadcrumbList","itemListElement":[{"position": 1, "@type": "ListItem", "item": {"@id": "https://www.care.com/c/", "name": "Community"}}, {"position": 2, "@type": "ListItem", "item": {"@id": "https://www.care.com/c/spaces/5/pets/", "name": "Pets"}}]},{"@context": "http://schema.org", "@type": "Article","description": "Most pet owners have to deal with the reality of pet care as soon as they come home with their new furry friend.&amp;nbsp; So for you newbies or struggling &quot;sophomore&quot; pet owners, here are some of the more popular pet care options and what you can expect. Dog Walking and ...", "image": {"url": "https://cdn.kinsights.com/content/images/kalik69-201809041609496533.jpg", "width": 520, "@type": "ImageObject", "height": 780}, "datePublished": "2013-06-26T09:09:00+00:00", "dateModified": "2018-05-04T16:10:12.398527+00:00", "publisher": {"logo": {"url": "https://cdn.kinsights.com/static/images/logo-crcm-black.png", "width": "414px", "@type": "ImageObject", "height": "77px"}, "@type": "Organization", "name": "Care.com"}, "name": "Pet Care Options", "author": {"@type": "Organization", "name": "Care.com"}, "headline": "Pet Care Options", "url": "https://www.care.com/c/stories/10250/pet-care-options/", "mainEntityOfPage": {"@type":"WebPage","@id":"https://www.care.com/c/stories/10250/pet-care-options/"}}]
    </script>`

You should now see a preview button:

![capture100](https://user-images.githubusercontent.com/36829233/45852201-de21fb80-bd81-11e8-8121-c690a2711a90.JPG)

And a search preview like this:

![capture101](https://user-images.githubusercontent.com/36829233/45852225-f8f47000-bd81-11e8-9abc-20247964ad9a.JPG)

You will notice I have moved your breadcrumbs out of the article markup and change the author to organization and removed sameAs attribute.

Hope this helps.

**Comment by mikedidthis** [comment]
Hi @OptimumGraph.

Thank you so much for the quick response! The changes / comments make sense so this issue is now resolved. 

Out of interest is the "preview" button documented anywhere? I had no idea the Structured Data Testing Tool had one.

**Comment by OptimumGraph** [comment]
Hi @mikedidthis 

I'm not aware of any in depth documentation for just the preview button apart from this link from Google [https://support.google.com/webmasters/answer/6398748#__RICH_CARD_HC](url)

If you follow the guides provided by Google here [https://developers.google.com/search/docs/guides/search-features](url) your structured data should work as expected.

**Comment by strayguevara** [comment]
We have a similar issue where the warning "Error in required structured data element" is appearing on AMP versions of our pages (but not on non-AMP versions).  The error is not resolved by the presence of the green 'preview' button.  We've described the issue in detail here: https://stackoverflow.com/questions/56639958/amp-pages-with-videoobject-returning-error-in-required-structured-data-element
