### ISSUE TITLE
Broken validator: the tag 'amp-skimlinks' is disallowed.

### ISSUE THREAD

**Issue by slocka** [ampproject/amphtml#19402]
## What's the issue?

`amp-skimlinks` tag is not allowed anymore by the validator.

`amp-skimlinks` was released last week and was considered valid by the validator until today or yesterday. It is now considered as invalid.

## How do we reproduce the issue?

https://validator.ampproject.org/ validator is showing an error "The tag 'amp-skimlinks' is disallowed."  when using  `<amp-skimlinks></amp-skimlinks>` tag. 

When testing with flag `#development=1` in a page with amp-skimlinks, a similar error happens in the console. See http://lepunk.co.uk/test_plugin.html#development=1

## Which AMP version is affected?

Latest but it was working a few days ago.

@Gregable @alin04

**Comment by slocka** [comment]
I am not familiar with the release process of the `validator.js` but I noticed that all the following releases seem to have the exact same code for`validator.js` despite some changes happening in the validator:
https://cdn.ampproject.org/rtv/001811132019350/v0/validator.js
https://cdn.ampproject.org/rtv/001811091519050/v0/validator.js
https://cdn.ampproject.org/rtv/001811091510240/v0/validator.js
https://cdn.ampproject.org/rtv/001811081843340/v0/validator.js
https://cdn.ampproject.org/rtv/001811061807340/v0/validator.js

However, when building validator.js for each of those releases on my local the code is different and `amp-skimlinks` is recognised as a valid tag.

I also noticed that this other recent change on the validator https://github.com/ampproject/amphtml/pull/19294/files is also not reflected in the live validator. 

Is it possible that the wrong validator.js has been released for the last releases? It seems that the validator.js code is stuck in a previous version.

@aghassemi @cvializ could you double check that the release has been done correctly?

**Comment by alin04** [comment]
@jridgewell for more context. The last JS validator deployment was done Nov 13. Justin, any chance the brotli process changed things?

**Comment by honeybadgerdontcare** [comment]
@slocka 	when a 	`layout` isn't specified, `container` is the default and `container` is not allowed for `amp-skimlinks`. The only allowed layout is 	`nodisplay`. Is there another issue you're facing with `amp-skimlinks`?

**Comment by honeybadgerdontcare** [comment]
Closing as this is expected behavior. If there is another issue then please let us know. The AMP validator is not released at the same time of code commit nor Runtime release.

**Comment by Gregable** [comment]
I think you are seeing a cached copy of the validator @honeybadgerdontcare

**Comment by slocka** [comment]
@honeybadgerdontcare 
Sorry, I pasted the minimum code which raises an error. The same error happens when using:
```
<!--
     This is the minimum valid AMP HTML document. Type away
     here and the AMP Validator will re-check your document on the fly.
-->
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
   <script async custom-element="amp-skimlinks" src="https://cdn.ampproject.org/v0/amp-skimlinks-0.1.js"></script>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
</head>
<body>
    <amp-skimlinks
        layout="nodisplay"
        publisher-code="123X456"
    >
    </amp-skimlinks>
</html>
```
There is defintely something wrong with the validator, any reference to "amp-skimlinks" has disappeared from the source code of `validator.js`. (I personally checked and it was there few days ago)

Could you please re-open the issue? This is impacting us and our publishers quite badly.

**Comment by slocka** [comment]
Thanks @Gregable. Some publishers have removed our extension from their site after seeing the error. Can you confirm that it's safe for our publishers to put the extension back even though https://validator.ampproject.org/ and other validation tools are raising errors?

I noticed that https://search.google.com/test/amp doesn't seem to raise any error and considers pages with`amp-skimlinks` extension as valid. As a general rule, can we consider https://search.google.com/test/amp as the only source of truth over other validators?

**Comment by Gregable** [comment]
> Can you confirm that it's safe for our publishers to put the extension back even though https://validator.ampproject.org/ and other validation tools are raising errors?

Yes, it is safe to add this extension.

**Comment by honeybadgerdontcare** [comment]
Note that search.google.com/test/amp should be giving the same result as validator.ampproject.org and that should never change. This is an unfortunate situation where the two diverge temporarily and will be fixed soon.

**Comment by honeybadgerdontcare** [comment]
According to validator.ampproject.org this is now fixed. Please let me know if you're seeing any additional issues.

**Comment by slocka** [comment]
@honeybadgerdontcare It seems to be fixed on the live validator 👍. However, when turning on the devchannel, the same issue is still happening on validator.ampproject.org. I am worried that this issue comes back next release. Has the root of the issue been identified and fixed?

**Comment by slocka** [comment]
@honeybadgerdontcare I confirm that the issue is still happening when devchannel is on, I tried in two different laptops, in incognito mode. Caching might be the reason why you don't see it. Here is how to reproduce the issue:

1 - Open a new incognito window.
2 - Go to https://cdn.ampproject.org/experiments.html
3 - Turn dev-channel experiment to "On"
4 - Go to https://validator.ampproject.org/
5 - Paste this code:
```html
<!--
     This is the minimum valid AMP HTML document. Type away
     here and the AMP Validator will re-check your document on the fly.
-->
<!doctype html>
<html ⚡>
<head>
  <meta charset="utf-8">
  <link rel="canonical" href="self.html" />
  <meta name="viewport" content="width=device-width,minimum-scale=1">
  <style amp-boilerplate>body{-webkit-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-moz-animation:-amp-start 8s steps(1,end) 0s 1 normal both;-ms-animation:-amp-start 8s steps(1,end) 0s 1 normal both;animation:-amp-start 8s steps(1,end) 0s 1 normal both}@-webkit-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-moz-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-ms-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@-o-keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}@keyframes -amp-start{from{visibility:hidden}to{visibility:visible}}</style><noscript><style amp-boilerplate>body{-webkit-animation:none;-moz-animation:none;-ms-animation:none;animation:none}</style></noscript>
   <script async custom-element="amp-skimlinks" src="https://cdn.ampproject.org/v0/amp-skimlinks-0.1.js"></script>
  <script async src="https://cdn.ampproject.org/v0.js"></script>
</head>
<body>
    <amp-skimlinks
        layout="nodisplay"
        publisher-code="123X456"
    >
    </amp-skimlinks>
</html>
```

Two errors will show:
- Custom Javascript is not allowed.
- The tag 'amp-skimlinks' is disallowed.

**Comment by Gregable** [comment]
I can confirm this isn't working on devchannel. Investigating.
