### ISSUE TITLE
AMP URL API not returning AMP URLs

### ISSUE THREAD

**Issue by mdiblasio** [ampproject/amphtml#19516]
## What's the issue?
The [ampUrls.batchGet API method](https://developers.google.com/amp/cache/reference/acceleratedmobilepageurl/rest/v1/ampUrls/batchGet) is returning error code "NO_AMP_URL" for canonical URLs that have live, valid AMP pages (that serve in Google Search).

## How do we reproduce the issue?
Examples:

- https://www.zales.com/rings
- https://www.samsung.com/us/smartphones/galaxy-s9/

**Comment by mdiblasio** [comment]
[Referenced question](https://stackoverflow.com/questions/53488756/amp-url-api-not-returning-valid-amp-page)

**Comment by torch2424** [comment]
Triagiang to @Gregable , as it kind of sort of relates to cache? Though I know the API is run somewhere else? Feel free to reassign 😄

**Comment by Gregable** [comment]
This is a Google product specific issue. Filed #120261467 internally to track.

**Comment by jgluk** [comment]
The two URLs in the first comment have been fixed. We are working to prevent this from happening again in the future.

**Comment by samparnell** [comment]
Still seeing this on a consistent basis. 
https://github.com/ampproject/amphtml/issues/23925
