### ISSUE TITLE
amp-list on shadow-dom doesn't render mustache template

### ISSUE THREAD

**Issue by iwoak** [ampproject/amphtml#21902]
## What's the issue?
amp-list on shadow-dom doesn't render mustache template from yesterday (17 April)

![image](https://user-images.githubusercontent.com/10278898/56364705-80f30900-61ef-11e9-870d-a909ba1e4b01.png)

## How do we reproduce the issue?
You can visit every ours detail article page on https://rep.repubblica.it for example https://rep.repubblica.it/pwa/intervista/2019/04/17/news/orlando_il_ministro_sappia_che_non_mi_faro_scavalcare_sono_pronto_a_denunciarlo_-224314656/ and you can look for vote and comments info and links at the right of "condividi" (share) link 

1. Go to our premium home page news site on https://rep.repubblica.it
2. Click on any link to an article detail page (eg https://rep.repubblica.it for example https://rep.repubblica.it/pwa/intervista/2019/04/17/news/orlando_il_ministro_sappia_che_non_mi_faro_scavalcare_sono_pronto_a_denunciarlo_-224314656/) 
3. Find share bar after the title and signature like this 
![image](https://user-images.githubusercontent.com/10278898/56365182-81d86a80-61f0-11e9-8447-6afa3034a5a8.png)
4. You can find only share label, miss vote and comments label

If you visit pure amp page at this url https://rep.repubblica.it/ws/detail/intervista/2019/04/17/news/orlando_il_ministro_sappia_che_non_mi_faro_scavalcare_sono_pronto_a_denunciarlo_-224314656/ and all works fine

Ours rest json services linked on src attribute at amp-list works fine and response with data and 200 http code.

## What browsers are affected?
Chrome, Firefox, Safari

## Which AMP version is affected?
1904091426070

**Comment by aghassemi** [comment]
Hi @iwoak.

Does this always happen? I have not been able to reproduce in Chrome/Safari/Firefox both comment and rating sections show up fine for me with 1904091426070 ( I am testing by going to https://rep.repubblica.it/pwa/generale/2019/04/17/news/iva_tria_non_esclude_i_rincari_lega_e_5_stelle_mai_con_noi_-224316802/ )

Also note that 1904091426070 went to production April 15

**Comment by aghassemi** [comment]
@iwoak 

The only time I was able to repro this was
1- clear cache
2- hit https://rep.repubblica.it instead of the article directly
3- click on an article.

In that case, I got the following errors from the service-worker:

```
  | Promise.then (async) |   |  
-- | -- | -- | --
  | (anonymous) | @ | service-worker.js:279
  | Promise.then (async) |   |  
  | (anonymous) | @ | service-worker.js:279
  | Promise.then (async) |   |  
  | i | @ | service-worker.js:279
  | (anonymous) | @ | service-worker.js:279
  | Promise.then (async) |   |  
  | r | @ | service-worker.js:279
  | (anonymous) | @ | service-worker.js:279
  | r | @ | service-worker.js:279
```

upon next refresh, everything worked and no `service-worker` errors appeared.

Any chance your service-worker updated around that time frame? I can see `amp-list` trying to fetch the endpoint but service worker fails to respond leaving it in loading mode.

**Comment by iwoak** [comment]
Hi @aghassemi and thanks for your replies, but I still see the problem and I can replicate it in both way (visiting directly detail page or navigate from home page).

![image](https://user-images.githubusercontent.com/10278898/56420609-fbc72d00-629e-11e9-91b4-188075031584.png)

I don't receive any error from service-worker :(

**Comment by aghassemi** [comment]
@iwoak Thanks, how often does this repro for you? (like, how many times after refreshing) I still haven't been able to hit it. Using Firefox 66 I get the following everytime i refresh 
![Screen Shot 2019-04-19 at 7 49 37 AM](https://user-images.githubusercontent.com/2099009/56429473-d70b8f00-6277-11e9-95f7-dacfceef0c7c.png)

There likely is some sort of a race condition here. Only recent change related to `amp-list` is https://github.com/ampproject/amphtml/pull/21512 adding @choumx to take a look as well.

**Comment by aghassemi** [comment]
Chatted with @prateekbh, he will take a look. I doubt that this is new but recent changes may have caused the race to be more obvious. I still haven't been able to repro more than couple of times.

**Comment by prateekbh** [comment]
While investigating this, I did observe that the social calls are failing intermittently. Screenshots attached.

This is pretty frequent and happened over a few refreshes
<img width="1679" alt="Screen Shot 2019-04-19 at 1 52 09 PM" src="https://user-images.githubusercontent.com/5960497/56443733-b4469e00-62aa-11e9-9051-fb8ed8979574.png">
![Uploading Screen Shot 2019-04-19 at 1.53.34 PM.png…]()

**Comment by prateekbh** [comment]
@choumx I found [this](https://github.com/ampproject/amphtml/blob/master/extensions/amp-list/0.1/amp-list.js#L344) which is similar to #19511. Should this be converted to `this.getAmpDoc()`

**Comment by justforfun** [comment]
I'm able to reproduce the problem on Chrome at every hit of this page:
https://rep.repubblica.it/pwa/intervista/2019/04/19/news/di_maio_sulla_legge_decidono_i_giudici_salvini_non_faccia_come_berlusconi_-224471120/

while on the plain AMP page everything is working as expected:

https://rep.repubblica.it/ws/detail/intervista/2019/04/19/news/di_maio_sulla_legge_decidono_i_giudici_salvini_non_faccia_come_berlusconi_-224471120/

I don't see any service worker related error
<img width="1132" alt="Schermata 2019-04-20 alle 23 21 01" src="https://user-images.githubusercontent.com/477983/56462408-07ac0f80-63c3-11e9-8a8c-ab78ad4b2c44.png">

**Comment by prateekbh** [comment]
Hi @justforfun, while we are trying to figure out the race condition can you please verify that the same happens for you if the service worker is not registered or is bypassed by devtools.

<img width="1106" alt="Screen Shot 2019-04-23 at 4 56 00 PM" src="https://user-images.githubusercontent.com/5960497/56623344-b54c3800-65e8-11e9-92e9-792fd995243d.png">

**Comment by iwoak** [comment]
Hi @prateekbh, both me and @justforfun has the same problem even with SW not registered or bypassed.

**Comment by prateekbh** [comment]
Thanks this helps us narrow down the problem 🙂

**Comment by sparhami** [comment]
I remember debugging a similar sort of issue with shadow DOM and `amp-access`'s template rendering (#17328). The problem had to do with `viewerCanRenderTemplates` returning `false` when called within Shadow DOM.

I did make a change to fix that portion (#17896), but it could still be a problem or something similar (perhaps the wrong amp doc is being used somewhere). Could also try the `ampdoc-closest` experiment (either disable it if it is enabled, or enable it if it is not).

**Comment by iwoak** [comment]
Hi @sparhami I have this problem every time so I could debug if you write me some instructions.
I confirm: `viewerCanRenderTemplates ` returning `false`

![image](https://user-images.githubusercontent.com/10278898/56787098-b2756100-67fb-11e9-981d-7657c51ae238.png)

![image](https://user-images.githubusercontent.com/10278898/56787126-d0db5c80-67fb-11e9-8199-2c4d689cfc07.png)

**Comment by iwoak** [comment]
I found a elaboration difference from amp pure page and amp in shadow dom:

- when callstack through in compileCallback here https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js 

![image](https://user-images.githubusercontent.com/10278898/56788149-edc55f00-67fe-11e9-8532-cab52aadb923.png)

`"ReferenceError: sc is not defined
    at eval (eval at sc (https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js:65:64), <anonymous>:1:1)
    at sc (https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js:65:64)
    at Y.push.f.Y.compileCallback (https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js:64:370)
    at Y.Gf (https://cdn.ampproject.org/shadow-v0.js:134:249)
    at new Y (https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js:63:275)
    at https://cdn.ampproject.org/shadow-v0.js:138:431"`

and after in console i can see

`Uncaught (in promise) TypeError: Cannot read property 'ownerDocument' of undefined
    at je (shadow-v0.js:formatted:2464)
    at Cm (shadow-v0.js:formatted:11638)
    at wm.f.observeHiddenMutations (shadow-v0.js:formatted:11626)
    at wm.f.setup (shadow-v0.js:formatted:11619)
    at shadow-v0.js:formatted:12984`

**Comment by sparhami** [comment]
> Hi @sparhami I have this problem every time so I could debug if you write me some instructions.
> I confirm: `viewerCanRenderTemplates ` returning `false`

Sorry I think I might have had that backwards. I think this may be fine.

**Comment by prateekbh** [comment]
just adding @choumx @dvoytenko if they have any idea

**Comment by iwoak** [comment]
@sparhami, what do you think about this?

> I found an elaboration difference from amp pure page and amp in shadow dom:
> 
> * when callstack through in `compileCallback` here https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js
> 
> ![image](https://user-images.githubusercontent.com/10278898/56788149-edc55f00-67fe-11e9-8532-cab52aadb923.png)
> 
> `"ReferenceError: sc is not defined at eval (eval at sc (https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js:65:64), <anonymous>:1:1) at sc (https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js:65:64) at Y.push.f.Y.compileCallback (https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js:64:370) at Y.Gf (https://cdn.ampproject.org/shadow-v0.js:134:249) at new Y (https://cdn.ampproject.org/rtv/011904200955460/v0/amp-mustache-0.2.js:63:275) at https://cdn.ampproject.org/shadow-v0.js:138:431"`

**Comment by gilbertococchi** [comment]
Hi all, I can confirm that the SW "service-worker.js:1 Uncaught (in promise) DOMException" errors because of Quota Errors are unrelated as I can get the Comments to work with the DOMException error there.

I've noticed that the error occurs 100% when this error is visible from the Console:

```
blob:https://rep.repubblica.it/8a96ddc0-0b73-4f68-b721-2b3b1b8fc296:6 Uncaught TypeError: self.reportError is not a function
    at qa.r.error (blob:https://rep.repubblica.it/8a96ddc0-0b73-4f68-b721-2b3b1b8fc296:6)
    at blob:https://rep.repubblica.it/8a96ddc0-0b73-4f68-b721-2b3b1b8fc296:78
```

blob:https://rep.repubblica.it/8a96ddc0-0b73-4f68-b721-2b3b1b8fc296

![Screenshot 2019-04-29 at 13 21 40](https://user-images.githubusercontent.com/329023/56893073-c7fbbc80-6a81-11e9-84cd-7d958c33db25.png)

Steps to reproduce constantly:
- Open New Anonymous Tab: 
- Browse https://rep.repubblica.it with Mobile Emulation "Pixel 2XL" and Network "Fast 3G".
- Wait for the Homepage to load entirely.
- Click on the first article to get the issue on Comments (wait for article to load entirely on Fast 3G emulation).

**Comment by prateekbh** [comment]
Will use this today to dig deeper today

**Comment by prateekbh** [comment]
Confirmed: I can reproduce this in an incognito window using the steps in: https://github.com/ampproject/amphtml/issues/21902#issuecomment-487543633

**Comment by sparhami** [comment]
The `self.reportError` part seems to be #20938.

@choumx Can we prioritize fixing this?

**Comment by prateekbh** [comment]
The stacktrace i am getting is pointing to https://github.com/ampproject/amphtml/pull/21687/files#diff-a244d3899d7cb3930087a9d566a46af9R259

Which should be fixed with #21976,I'll re-check tomorrow with the dev channel once the opt-in is rolled out

**Comment by gilbertococchi** [comment]
Hi Prateek, thank you for checking on this.

Did you manage to test it on Dev Channel with the fix?

I also noticed sometimes randomly the Comments via amp-list loads even when I am getting the "self.reportError is not a function" error...

<img width="1037" alt="Screenshot 2019-04-30 at 17 10 30" src="https://user-images.githubusercontent.com/329023/56972210-dffb3b00-6b6a-11e9-81ff-a24d4b919304.png">

**Comment by prateekbh** [comment]
@gilbertococchi the dev channel fix will be available today, will update the thread once I check it. If there are any more errors they are definitely masked by this thus waiting for this fix.

Also the `self.reportError` is a known error and I guess @choumx/ @sparhami are working on it

**Comment by prateekbh** [comment]
Hi I tested this with canary: https://cdn.ampproject.org/rtv/001904301721170/shadow-v0.js with a custom redirect and seems like it fixes the problem.

The canary will be available as an opt-in tomorrow and you should be able to check with it as well.

If everything works i'll continue adding tests around this.

**Comment by prateekbh** [comment]
Hi I just tested with the dev channel and it seems to be working for me with the above steps.

Can you please check and revert

**Comment by iwoak** [comment]
Hi @prateekbh with the dev channel it works fine even for me. Thanks a lot!
When could be made a release? Just for understand if we can wait the release or we must found an other temp fix.

**Comment by prateekbh** [comment]
I guess I can get this cherry-picked for you today :)

**Comment by prateekbh** [comment]
Hi @iwoak We did a cherry pick of a suspected change whose fix is available in production now. But I can still the issue.

I'll try to look for any other suspects.

The complete canary will reach production on Tuesday, but will try to ask if this can be done any sooner.

**Comment by prateekbh** [comment]
// @cathyxz

**Comment by iwoak** [comment]
I still see the issue too, but thanks a lot @prateekbh for cherry pick!

**Comment by mattwomple** [comment]
@prateekbh Based on these comments:

[gilbertococchi](https://github.com/ampproject/amphtml/issues/21902#issuecomment-487991479)

> I've noticed that the error occurs 100% when this error is visible from the Console

[aghassemi](https://github.com/ampproject/amphtml/issues/21902#issuecomment-484595962)

> The only time I was able to repro this was
> 1- clear cache
> 2- hit https://rep.repubblica.it instead of the article directly
> 3- click on an article.

... the issue sounds directly related to #17532 . If this is the case, it can be remedied in one of two ways:

- AMP project pushes #21854 to production
- rep.repubblica.it adds a "cleanup" step at the same time they call [`shadowDoc.close()`](https://github.com/ampproject/amphtml/blob/master/spec/amp-shadow-doc.md#shadow-doc-api):

      delete window.services['amp-worker'];

**Comment by cathyxz** [comment]
So @prateekbh figured out that 1904091426070 was the release that broke it and our new dev channel contains changes that fix it. A breakpoints indicate that the main difference here (to `<amp-list>`) between throttling to Fast 3G is whether or not the `updateBindings_` promise ever returns to result in a call to `render_`, which is the function that appends the elements to the DOM. 

`updateBindings_` in both cases, end up waiting for a `scanAndApply` function in `bind-impl.js` which never returns in the Fast 3G case. The relevant code is: 

https://github.com/ampproject/amphtml/blob/84a002d004fdefa3eae85ef8e8647b9f7abfc472/extensions/amp-bind/0.1/bind-impl.js#L383-L389

In the Fast 3G case where the bug repros, a breakpoint on L387 at `rescan` never hits, whereas it does when we unthrottle the network. 

If I may venture a hypothesis, the most closely related PR that might cause this from 1904091426070 was #21763, the most closely related PR that might fix it might be #21854 as @mattwomple says.

**Comment by prateekbh** [comment]
// @choumx as he might have better idea

**Comment by choumx** [comment]
Cathy was on the right track. The problem is there are actually two shadow AMP docs on this page: (1) the main article and (2) a subscriptions widget in the top right corner. 

Both of these shadow docs use amp-bind, but amp-bind's worker is only scoped to support 1 doc per window. This is the cause of the worker console error -- the second doc's amp-bind initialization always fails (before the fix in canary).

So the race is actually "which page gets initialized first". If the article doc happens to be initialized after the subscriptions, then the initialization promise never resolves. This means amp-list render gets stuck waiting for amp-bind to rescan.

The "fix" in canary just ignores this error and overwrites the existing worker state. This likely breaks amp-bind functionality somewhere, but it does allow the promise to resolve. :)

The long-term fix should be to (A) support multiple docs in amp-bind's worker and (B) make cross-extension APIs more resilient (promise timeouts etc.) and (C) fix error logging in web worker. Happy to spend some cycles on this next week.

**Comment by prateekbh** [comment]
Thank you @choumx 🤗 
@iwoak  the canary rolls out to production on tuesday, but if you need an immediate fix you can load `shadow-v0.js` from `https://cdn.ampproject.org/rtv/011904301721170/shadow-v0.js` instead of `https://cdn.ampproject.org/shadow-v0.js`

**Comment by iwoak** [comment]
Thanks a lot @prateekbh  and @choumx! the problem is very clear now.
We look forward fo tuesday production release and we'll work to remove the less important second amp shadow dom (subscriptions widget in the top right corner)

**Comment by iwoak** [comment]
thanks a lot, now all works fine online for us on rep.repubblica.it.  Until the long-term fix is published maybe you could put a note on the documentation about only one shadow amp tip.
