### ISSUE TITLE
Restarting integration test in travis should set both stable and beta checks to queued

### ISSUE THREAD

**Issue by jridgewell** [ampproject/amphtml#25492]
When I restart the integration build in Travis, only the "beta" integration tests update to the yellow "queued" state. We should make both be yellow:

![Screen Shot 2019-11-07 at 4 38 08 PM](https://user-images.githubusercontent.com/112982/68430811-ca507900-017e-11ea-9dfa-d1dbaf97870c.png)

**Comment by rsimha** [comment]
The "beta" tests are in the queued state because they were never run during the first attempt (because "stable" failed).

It should be possible to reset every test suite's status when it's (re)started.

**Comment by rsimha** [comment]
I've noticed this several times in the recent past, and agree that it's a relatively easy fix that can improve the usability of our test statuses. Bumping to P2.

**Comment by danielrozenberg** [comment]
(:%s/travis/github actions/) (%s/stable|beta/firefox|safari|edge|ie/) - I believe this is fixed already, given the way that @rsimha rewrote the tests and [how they get reported](https://github.com/ampproject/amphtml/blob/6ae6dbcd4c2198f3b355b630cfc5693afc051abe/build-system/pr-check/cross-browser-tests.js#L111) by each individual job on GitHub Actions. @rsimha do you agree?

**Comment by rsimha** [comment]
You're mostly correct. I think one part of this issue still remains: when a testing job fails and is restarted, we call `reportTestStarted()` at the beginning. I'm not sure if that removes the red X mark on the commit status. If it does, we're good. If not, any way to get it to reset the "failed" status of the check to "queued" while the tests are rerun?

**Comment by danielrozenberg** [comment]
When we restart it and call `reportAllExpectedTests()` it resets all of them to yellow - `reportTestStarted()` happens on individual test groups

**Comment by rsimha** [comment]
The way to address this issue is to have `reportTestStarted()` be called for all test types that will be run by a job, at the start of that job. This will make things clear when a failing job that runs multiple test types is restarted.
