### ISSUE TITLE
Error with displaying [amp-auto-ads] No anchor element found

### ISSUE THREAD

**Issue by lumaypl** [ampproject/amphtml#26734]
**Please only file reports about bugs in AMP here.**
If you have a bug for AMP please fill in the following template. Delete everything except the headers (including this text).

## What's the issue?
Since 9 Feb 2020 AMP Auto Ads didn't display on my website - I have  nothing change on in code / any updates...

Below pls find error find in Console:
[amp-auto-ads] No anchor element found

It is affected only on AMP version posts for amp-auto-ads (regular desktop and mobile ads re OK)...

## How do we reproduce the issue?
All AMP posts on website:
https://mobirank.pl/
for example:
https://mobirank.pl/2020/02/10/raport-zarobki-i-rynek-pracy-it-w-polsce-w-2019-roku/amp/

## What browsers are affected?
all

## Which AMP version is affected?
1.4.2

**Comment by mattwmc** [comment]
I have the same problem.

**Comment by luxmike77** [comment]
I have the same problem in 2 sites since 11 Feb

**Comment by Sshuichi** [comment]
Any update on this guys? Having the same issue..

**Comment by eperezf** [comment]
I have the same issue

**Comment by Sshuichi** [comment]
This is the SOF issue and how I fixed it. 
https://stackoverflow.com/questions/61726920/adsense-return-the-wrong-selectors-on-my-amp-pages

**Comment by eperezf** [comment]
I already have the <article> tag inserted. Still having the error.

**Comment by Sshuichi** [comment]
Can you post the placement answer from Google?

**Comment by eperezf** [comment]
I'm sorry, what is the placement answer?

**Comment by Sshuichi** [comment]
Read the SOF question, it's the response you get from this link: 
`https://pagead2.googlesyndication.com/getconfig/ama?client=ca-pub-7726580065556509&plah=[site_url]&ama_t=amp&url=[Page_url]&__amp_source_origin=[site_url]`

Check your network tab

**Comment by eperezf** [comment]
I searched in the network tab and didn't find that link. 
[https://pisapapeles.net/subtel-lanza-consulta-publica-sobre-ciberseguridad-en-redes-de-telecomunicaciones/amp](Here's an example.)

**Comment by Sshuichi** [comment]
I do see ads on your site, but I don't think the auto ads are implemented correctly. 
Try pasting the snippet code right after the body tag

**Comment by mattwmc** [comment]
I have the article tag, too. Doesn't work.

**Comment by nabaleka** [comment]
Using the Newspaper WordPress theme and WordPress AMP Plugin I am also experiencing this issue.

**Comment by mattwmc** [comment]
I'm using Drupal. Seems to be a problem where adsense is not detecting certain tags for some reason.

**Comment by mileticslobo** [comment]
Problem still here.

**Comment by MarcoValeri** [comment]
I have the same problem

**Comment by mattwmc** [comment]
I've since got someone to create a script that places an add after every 3rd or whatever paragraph. Might want to go that route.

**Comment by jcvignoli** [comment]
I have the same problem. For almost one year, now, with no fix that one could forsee...
