### ISSUE TITLE
AMP viewer sending wrong URL when infinite scroll is triggered?

### ISSUE THREAD

**Issue by AndrewKGuan** [ampproject/amphtml#27064]
Please see this video and watch the end of the URL changes:
https://youtu.be/Clt6RMjopSI

The AMP viewer is not setting the URL correctly, instead it's setting the path to "/v/s/"

**Comment by wassgha** [comment]
Hey @AndrewKGuan ! Thanks for reporting, is this `amp-next-page@1.0` or `0.1`?

**Comment by AndrewKGuan** [comment]
Hi, thanks for taking a look!  It's 0.1.  Here's the page's url:
https://www.forbes.com/sites/scottmendelson/2020/03/01/onward-pixar-my-hero-academia-impractical-jokers-wendy-weekend-box-office/amp/

**Comment by wassgha** [comment]
Do you mind checking if it's fixed in `1.0` (please test locally since the page won't be valid AMP yet)

**Comment by AndrewKGuan** [comment]
Sorry I'm not sure if I can do that.  I can override the source code from forbes.com locally on my browser, but I'm not sure how I can put it inside a viewer to check.

**Comment by nainar** [comment]
Forbes should be using version 1.0 right now. Andrew can you have them check if they are still getting this issue.
