### ISSUE TITLE
Adobe-analytics on amp-analytics `vars` transforms multibyte characters to `?`

### ISSUE THREAD

**Issue by ka2jun8** [ampproject/amphtml#27379]
If anyone knows about adobe analytics config rewriter, please help me solving for this problem.

## What's the issue?
 - We use adobe analytics by amp-analytics.
 - The `vars` transforms multibyte characters to `?` after 3/18 by config rewriter.
 - We checked adobe analytics config is changed.
   - https://github.com/ampproject/amphtml/releases/tag/2003101714470
   - before: https://cdn.ampproject.org/rtv/012003031842100/v0/analytics-vendors/adobeanalytics.json
   - after: https://cdn.ampproject.org/rtv/012003101714470/v0/analytics-vendors/adobeanalytics.json
   - https://github.com/ampproject/amphtml/pull/27078
 - Adobe config rewriter is not worked for multibyte characters.
 - We are wating for answer by adobe team.
 - request and response example image:

![image](https://user-images.githubusercontent.com/12580072/77393679-e9c00980-6de0-11ea-91c1-58cb1f8e038e.png)

## How do we reproduce the issue?

1. send POST request to `https://ampconfig.sc.omtrdc.net/aa/services/ampconfig` include multibyte characters in request body.

```
curl --request POST \
  --url https://ampconfig.sc.omtrdc.net/aa/services/ampconfig \
  --header 'content-type: application/json' \
  --data '{
  "requests": {
    "base": "https://${host}/${random}",
    "pageView": "${base}",
    "click": "${base}"
  },
  "vars": {
    "pageName": "top",
    "channel": "categories",
    "prop26": "こんにちは",
    "prop27": "你好",
    "host": "example.com",
    "reportSuites": "reportsuit",
    "prop47": "sample"
  },
  "triggers": {}
}'
```

## What browsers are affected?

All browsers

## Which AMP version is affected?

version: 2003101714470

**Comment by micajuine-ho** [comment]
Hi @ka2jun8 to clarify the problem: You are sending multi-bytes characters to Adobe Analytics' config rewriter and their endpoint is returning `??`. 

Is this correct?

**Comment by ka2jun8** [comment]
It is correct.

**Comment by ka2jun8** [comment]
I cannot find the documents of Adobe Analytics' config rewriter, so I do not know why need it, because my adobe analytics config did not change without multi-bytes characters.
At least I do not need to rewrite my config of my adobe analytics, so I want to skip rewrite process if it can.

**Comment by micajuine-ho** [comment]
Hmm.. currently there is no way avoid the config rewriter. Maybe we discuss the ability to skip the config rewriter process? 

What are you thoughts @zhouyx ?

**Comment by zhouyx** [comment]
Add @cory-work

I think this should be fixed by Adobe analytics. 

I also don't think the inline config should overwrite the configRewriter setting. It is an important feature for analytics vendor to provide service.

**Comment by cory-work** [comment]
I'll take a look

**Comment by ka2jun8** [comment]
> I also don't think the inline config should overwrite the configRewriter setting. It is an important feature for analytics vendor to provide service.

I am convinced.
If the config rewriter work properly for multi-bytes characters, I have no problem.

Thanks @cory-work !

**Comment by cory-work** [comment]
This wasn't a bug with AMP but rather the config rewriter. A fix has been deployed and appears to be working

**Comment by ka2jun8** [comment]
This bug is still happening, so your fixed version has not released yet, right?
I'm looking forward to seeing the fix released.

**Comment by cory-work** [comment]
> This bug is still happening, so your fixed version has not released yet, right?
> I'm looking forward to seeing the fix released.

Could you provide an example?

**Comment by ka2jun8** [comment]
The following cURL example is the same that it writes in this issue body.

```
curl --request POST \
  --url https://ampconfig.sc.omtrdc.net/aa/services/ampconfig \
  --header 'content-type: application/json' \
  --data '{
  "requests": {
    "base": "https://${host}/${random}",
    "pageView": "${base}",
    "click": "${base}"
  },
  "vars": {
    "pageName": "top",
    "channel": "categories",
    "prop26": "こんにちは",
    "prop27": "你好",
    "host": "example.com",
    "reportSuites": "reportsuit",
    "prop47": "sample"
  },
  "triggers": {}
}'
```

response:

```
{
  "requests": {
    "base": "https://${host}/${random}",
    "pageView": "${base}",
    "click": "${base}"
  },
  "vars": {
    "pageName": "top",
    "channel": "categories",
    "prop26": "?????",
    "prop27": "??",
    "host": "example.com",
    "reportSuites": "reportsuit",
    "prop47": "sample"
  },
  "triggers": {}
}
```

**Comment by cory-work** [comment]
Thanks @ka2jun8 the fix wasn't deployed everywhere. Should be resolved in a few minutes

**Comment by micajuine-ho** [comment]
@ka2jun8 Can you verify that the fix was deployed?

**Comment by ka2jun8** [comment]
@cory-work @micajuine-ho 
I checked the problem has been resolved. Thank you !!!
