### ISSUE TITLE
Saucelab tests are continuously failing 

### ISSUE THREAD

**Issue by lannka** [ampproject/amphtml#3561]
All the [recent build](https://travis-ci.org/ampproject/amphtml/builds) are failing: https://travis-ci.org/ampproject/amphtml/builds/137291477

```
Firefox 45.0.0 (Linux 0.0.0) error page "before each" hook for "should show the body in error test" FAILED
    Failed to find errors. HTML
Chrome 48.0.2564 (Linux 0.0.0)  "after each" hook for "all components should get loaded" FAILED
    Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
Edge 13.10586.0 (Windows 10 0.0.0) Rendering of one ad with ad script should create an iframe loaded with ad script FAILED
    Error: Unable to get property 'document' of undefined or null reference (/tmp/7192c6efe6dfe345244179c1f1307496.browserify:27121 <- /home/travis/build/ampproject/amphtml/test/integration/test-amp-ad-doubleclick-with-script.js:92:8)
(Many other errors for Edge 13) ...
```

**Comment by ericlindley-g** [comment]
Looks like this is fixed, but temporarily putting in fixit in case there is more outstanding work

**Comment by lannka** [comment]
The continuous build is still failing from time to time, but that's different issues causing the flakiness. Tracked elsewhere.

**Comment by muxin** [comment]
Seems like the test is still failing
`Edge 14.14393.0 (Windows 10 0.0.0) error page "before each" hook for "should show the body in error test" FAILED`
Shall we skip this test on Edge too?
