### ISSUE TITLE
amp-sidebar+amp-accordion do not render amp-img for sections pre-expanded

### ISSUE THREAD

**Issue by juliantoledo** [ampproject/amphtml#3586]
## Short description of your issue:

amp-sidebar+amp-accordion do not render amp-img for sections pre-expanded
## How do we reproduce the issue?
1. Create an amp-sidebar with an amp-accordion inside
2. Create a `<section expanded>` with an amp-img inside.
3. The image is not rendered by default (it shows the alt), it will be drawn on windows resize or after re-expanding the section.
## What browsers are affected?

Does not work on Chrome or Safari
## Which AMP version is affected?

Code:
 <amp-sidebar id='sidebar' layout="nodisplay">  
      <amp-img class='sidebar-close-image' src="/img/ic_chevron_left_black_24dp_2x.png" width="32" height="32" alt="Home" on="tap:sidebar.close" role="button" tabindex="0"></amp-img>

```
  <div class="topheader">
    <a href="/" class="homelogo">AMP by Example</a>
  </div>
  <amp-accordion>
    <section  >
      <h4>
        <div class="item">Introduction</div>
      </h4>
      <div>
        <div class="item">
          <a class="" href="/introduction/hello_world/">Hello World
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/introduction/how_to_publish_amps/">How to publish AMPs
            </amp-img>
          </a>
        </div>
      </ul>
    </section>
    <section expanded >
      <h4>
        <div class="item">Components</div>
      </h4>
      <div>
        <div class="item">
          <a class="selected" href="/components/amp-access/">amp-access
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-accordion/">amp-accordion
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-ad/">amp-ad
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-anim/">amp-anim
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-audio/">amp-audio
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-brightcove/">amp-brightcove
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-carousel/">amp-carousel
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-dailymotion/">amp-dailymotion
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-facebook/">amp-facebook
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-fx-flying-carpet/">amp-fx-flying-carpet
            <amp-img src="/img/ic_experiment_black_2x_web_18dp.png" width="18" height="18" alt="experimental">
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-iframe/">amp-iframe
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-image-lightbox/">amp-image-lightbox
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-img/">amp-img
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-instagram/">amp-instagram
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-install-serviceworker/">amp-install-serviceworker
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-lightbox/">amp-lightbox
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-list/">amp-list
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-pinterest/">amp-pinterest
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-sidebar/">amp-sidebar
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-social-share/">amp-social-share
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-soundcloud/">amp-soundcloud
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-sticky-ad/">amp-sticky-ad
            <amp-img src="/img/ic_experiment_black_2x_web_18dp.png" width="18" height="18" alt="experimental">
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-twitter/">amp-twitter
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-user-notification/">amp-user-notification
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-video/">amp-video
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-vimeo/">amp-vimeo
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-vine/">amp-vine
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/components/amp-youtube/">amp-youtube
            </amp-img>
          </a>
        </div>
      </ul>
    </section>
    <section  >
      <h4>
        <div class="item">Advanced</div>
      </h4>
      <div>
        <div class="item">
          <a class="" href="/advanced/amp-user-notification_with_server_endpoint/">amp-user-notification with Server Endpoint
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/advanced/how_to_create_interactive_amp_pages/">How to create interactive AMP pages?
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/advanced/image_galleries_with_amp-carousel/">Image Galleries with amp-carousel
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/advanced/integrating_videos_in_amp_an_overview/">Integrating Videos in AMP: an Overview
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/advanced/long_list_of_amp-instagram_embeds/">Long List of amp-instagram Embeds
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/advanced/using_the_google_amp_cache/">Using the Google AMP Cache
            </amp-img>
          </a>
        </div>
        <div class="item">
          <a class="" href="/advanced/video_carousels_with_amp-carousel/">Video Carousels with amp-carousel
            </amp-img>
          </a>
        </div>
      </ul>
    </section>
  </amp-accordion>
</amp-sidebar>
```

**Comment by ericlindley-g** [comment]
@sriramkrish85  Slotting in backlog, but feel free to correct/update the milestone as needed

**Comment by sriramkrish85** [comment]
@juliantoledo could you give me a link to an example page? 
You could use this to deploy AMP on a cloud and share the link.

**Comment by mkhatib** [comment]
@sriramkrish85 this could be also related to #3084

**Comment by juliantoledo** [comment]
Hi @sriramkrish85, I am staging it here:
https://abe-stage.firebaseapp.com/components/amp-access/
That page keeps the the "components" section expanded and you can see two images missing for the experimental icons until you colapse/reopen the section or you change the size of the browser window.

**Comment by sriramkrish85** [comment]
@juliantoledo Thanks for filing the bug!

@mkhatib , i guess this would also solve it not sure - #3444

**Comment by juliantoledo** [comment]
Now, the close icon image is missing and when I open the sidebar I get:
`base-element.js:585 Uncaught TypeError: this.c.scheduleLayout is not a functionJSCompiler_prototypeAlias.scheduleLayout @ base-element.js:585(anonymous function) @ amp-sidebar.js:153`
And when I close it:
`base-element.js:593 Uncaught TypeError: this.c.schedulePause is not a functionJSCompiler_prototypeAlias.schedulePause @ base-element.js:593(anonymous function) @ amp-sidebar.js:179JSCompiler_prototypeAlias.Wd @ vsync-impl.js:335`

**Comment by sriramkrish85** [comment]
@cramforce looks like a compilation issue

**Comment by ericlindley-g** [comment]
FWIW: @kul3r4 was getting something similar for amp-live-list as well

**Comment by cramforce** [comment]
This is canary only. @erwinmombay has a fix.
@ericlindley-g Lets not put "Major breakages" into backlog :)

**Comment by cramforce** [comment]
Fixed by #3628

**Comment by juliantoledo** [comment]
@cramforce We still have the issue, is it out in prod? could it be something on our side?
https://ampbyexample.com/components/amp-access/

**Comment by cramforce** [comment]
That appears to be unrelated to the bug fix.

@sriramkrish85 PTAL

**Comment by pratham2003** [comment]
I'm experiencing a similar problem as @juliantoledo but mine is only related to pre-expanded accordions.

Directly opening the article doesn't reproduce this issue : https://www.bijlibachao.com/top-ten-appliances/best-air-conditioner-ac-window-split-hitachi-lg-carrier-samsung-electricity-consumption-tonnage-in-india.html?isamp=1

Link with the issue : https://www.google.co.in/amp/s/www.bijlibachao.com/top-ten-appliances/best-air-conditioner-ac-window-split-hitachi-lg-carrier-samsung-electricity-consumption-tonnage-in-india.html%3Fisamp%3D1

Screenshot of the issue (on above link) : http://prntscr.com/f5g0fe

**Comment by ericlindley-g** [comment]
@aghassemi, with @camelburrito OOO do you know if anyone is taking a look at this? Thanks!

**Comment by camelburrito** [comment]
@ericlindley-g  
This should have been fixed long ago.  Are we prioritizing this now?
@pratham2003 
Img seem to be loading now (on page load) on the same url, is there are specific browser/os config that we should look at

**Comment by camelburrito** [comment]
<img width="496" alt="screen shot 2017-05-08 at 10 11 36 am" src="https://cloud.githubusercontent.com/assets/1037311/25815896/2d9a928e-33d7-11e7-97d9-a709b727d68b.png">

**Comment by pratham2003** [comment]
@camelburrito I'm not sure why its working now. Earlier it wasn't. The images used to appear only when I changed the orientation of the browser earlier (resize event as described in the original issue above).

Few hours ago the issue occurred in my phone's chrome browser + chrome desktop emulating a Galaxy S5.

**Comment by pratham2003** [comment]
Oh actually wait, I just tried something and have the steps to reproduce. It only happens when opening the article from a google result.

1) Google search for 'bijlibachao top inverter ACs'
2) Click on the 1st result (the article mentioned earlier should open)
3) Scroll down, issue should be visible

**Comment by camelburrito** [comment]
I was able to repro the issue as @pratham2003 said above. 

One additional info - reload the viewer and the image loads. 

This looks like a viewer/scheduling issue.

CC - @ericfs @chenshay @jridgewell

**Comment by jridgewell** [comment]
Let's open a new bug report.

**Comment by aghassemi** [comment]
@camelburrito @jridgewell I think this is just a race, not related to viewer. 
One possible race condition is:
1- amp-accordion.js loads, CSS is injected, hides everything in accordion.
2- runtime does a pass (it does not layout image inside accordion since it is hidden)
3- accordion's `buildCallback` is called, adds 'i-amphtml-accordion-header' now all of a sudden things are visible but too late for runtime to know.

now, if accordion adds `'i-amphtml-accordion-header' in a `mutateElement` runtime would get the signal, so PR#9221 for that fix.

but I also want to make sure this race condition legit. Should runtime wait for all components to build before doing a pass? (I assume not otherwise it has to wait for every script to load before laying out anything).

**Comment by camelburrito** [comment]
CC @dvoytenko

**Comment by pratham2003** [comment]
Just an update : We've temporarily switched to a CSS based accordion instead. We can switch back to the amp-accordion when its fixed to test.

**Comment by aghassemi** [comment]
@pratham2003 fix will be in prod in 10 days or so.

**Comment by thebinarium** [comment]
This is still happening under almost identical circumstances as described in the original report, but in my case it's a nested `<amp-lightbox>` -> `<amp-accordion>` -> `<amp-img>`. Setting the accordion to `expanded` ensures that the images are always loaded when the `lightbox` is opened, but this is not a viable workaround for our use case.

**Comment by aghassemi** [comment]
@thebinarium Thanks for reporting, do you mind creating a new GitHub issue? Thanks you!

**Comment by thebinarium** [comment]
@aghassemi can do!
