### ISSUE TITLE
<amp-sidebar> is scrolling back to the page top on local navigation

### ISSUE THREAD

**Issue by mdziekon** [ampproject/amphtml#4184]
Consider the following Sidebar code:

``` html
<amp-sidebar id="sidebar" layout="nodisplay" side="right">
    <ul>
        <li>
            <a href="#section1">Section 1</a>
        </li>
        <li>
            <a href="#section2">Section 2</a>
        </li>
        <li>
            <a href="#section3">Section 3</a>
        </li>
    </ul>
</amp-sidebar>
```

As you can see, I'm trying to create a simple "local" page nagivation that would jump between three sections using element ID.  
The problem is, that when the sidebar is closed, page returns to the page top (and it clears the browser's URL, by stripping the `#section1` part completely).

I think it's not a behavior that one would expect from this kind of component, and it completely defeats the concept of local navigation. If it is intentional, please provide an information and explanation in the documentation of this component.

**Comment by dvoytenko** [comment]
@mdziekon This is pretty interesting case. I see why it'd not work right now. `amp-sidebar` pops the history when it's canceled so the navigation is canceled. It's indeed important to pop the history stack to keep it tidy. What we need to figure out is how to defer the navigation after the stack is popped (or the other way around).

/to @sriramkrish85 - I believe this is an important case. Let's discuss.

**Comment by ericlindley-g** [comment]
+1 on this being an important case to support

**Comment by ericlindley-g** [comment]
@sriramkrish85   — Slotting in "pending triage" for now. please update the milestone when you have a sense of when work will start. Thanks!

**Comment by i049382** [comment]
I too am struggling with this behaviour

**Comment by dvoytenko** [comment]
Ping @sriramkrish85

**Comment by sriramkrish85** [comment]
Looks like the historyAPI is stripping off the breadcrumb.

I debugged that something is wron with this line of code, but not sure why pop would strip the `#id` from the url
```javascript
    if (this.historyId_ != -1) {
      this.getHistory_().pop(this.historyId_);
      this.historyId_ = -1;
    }
```

https://github.com/ampproject/amphtml/blob/master/extensions/amp-sidebar/0.1/amp-sidebar.js#L185

**Comment by dvoytenko** [comment]
@sriramkrish85 Correct. I described the actual flow above.

**Comment by Alexandre-Georges** [comment]
I have the same issue

**Comment by aghassemi** [comment]
@dvoytenko @sriramkrish85 My suggestion is to have AMP rewrite all anchors that have hash-based navigation to do it via JS (ie. `elem.scrollIntoView`) Aside from the sidebar issue, AMP relies on the hash for other purposes, so we should not allow `<a>` to change it.

If we take control over `<a href='#whatever'>`, then we can fix this issue and also provide a better UX (e.g. Sidebar closing automatically on local navigation)

If no objection, I will send a PR soon to discuss. We can restrict the rewrite to `<a>` inside sidebar for now but I think we should extend it to all links to avoid hash changing via user action.

**Comment by sriramkrish85** [comment]
@aghassemi yes that is what we had in mind

**Comment by eike-hass** [comment]
@aghassemi we implemented a navigation based anchor links that does not the use `amp-sidebar`. Would your proposed change to all anchor links interfere with these kind of navigations?

**Comment by aghassemi** [comment]
@eike-hass it will change the underlying mechanism of how the local navigation links jump to the page content on tap but will not break them. Essentially `<a href="#someId>` will not update the Url fragment anymore and we will use JS to scroll to `#someId` and push to browser history manually. 

If you have a live link to the page you have, please let me know so I can add it to my test cases. Thanks!

**Comment by mkhatib** [comment]
@dvoytenko what do you think of @aghassemi suggestions above?

**Comment by sriramkrish85** [comment]
@mkhatib - both me an @dvoytenko thought that was the way to go!

**Comment by mkhatib** [comment]
This is easy to do. We're already handling scrolling to the element with JS. So we'd have to drop the following calls:

````javascript
    win.location.replace(`#${hash}`);
```

And probably
```javascript
    history.push(() => {
      win.location.replace(`${curLoc.hash || '#'}`);
    });
```

The problem with this is this would break the `:target` css selector. Maybe we can keep the `replace` statement but drop pushing to history.

@dvoytenko do you see any problems with this approach? Will update the previous PR with this.

**Comment by dvoytenko** [comment]
@mkhatib Do changes to `document-click` solve issues for all use cases? If I understand right, we currently only install click interceptor for iframe'd case.

**Comment by mkhatib** [comment]
Yeah correct. We only install on iframed docs.

**Comment by dvoytenko** [comment]
Ok. So what's the plan? Will it still be broken in standalone? Or will we extend document click to standalone?

**Comment by mkhatib** [comment]
Ok, I wanna work on the other bug separately and see if we can get to this one, as I think these are two different issues. 

I don't fully agree yet on the idea of popping history when sidebar is manually closed. This should just push another history to the browser instead. Otherwise the any history that happened during that navigations are gone.

* Open Sidebar
* #link1
* #link2
* Close Sidebar

* Hit back should re-open sidebar. Instead this is currently broken because closing sidebar also pops the history if opening sidebar.

I propose we change that behavior from popping to just pushing another state to the history. I think it's the right thing to do.

**Comment by aghassemi** [comment]
@mkhatib 

I expect tapping `link1` in the sidebar to close the sidebar, so I don't think we can have a `open > link 1 > link2 > close` sequence, instead it will be `open > link1 > close > open > link2 > close`

I also think closing sidebar should pop the open from history otherwise the history gets really messy (picture `open > close > open > close`) and back button opening a sidebar is not a pattern I have seen in native or mobile web.

**Comment by mkhatib** [comment]
Actually sidebar doesn't close when tapping a link - I know people probably are divided on this, but maybe we can loop in Abbey and see what she thinks about the UX of clicking a link in sidebar - should it close it or not. Or we can expose an attribute about this like `close-on-navigation`.

I get the case where history get messy, I don't think this is an issue we need to handle. OR at least we can have a special case for when `close` happen right after `open`, not sure if we can peak in history now and pop `open` on close only if there was no history in between. (Similar implementation could do the popping and replay the history).

Another reason I don't like popping open on close is this: `open > close` what does hitting `back` now do? My understanding it should re-open the sidebar - but in the case we have already popped open, this might do something completely different. No?

I still think dropping pop on close is the right thing, we can handle that special case of consecutive open-close-open-close in this scenario.

**Comment by camelburrito** [comment]
@mkhatib i think it should close on click too (only for #bookmark links )

**Comment by mkhatib** [comment]
**Camel Burrito** I think that would actually make it easier to fix if we're taking the should close on click approach. If we can pop history before actually handing the click then things would work out terrific!

@dvoytenko what do you think about changing the `amp-sidebar` behavior to close. I am not entirely sure which handler is first called but we probably can capture the click inside sidebar and decide to pop history before the actual click to scroll to the element happen.

**Comment by ericlindley-g** [comment]
@abby001

* I think using a close-on-navigation (or similar attribute) is the way to go on this, since the sidebar could be used for a lot of other UI, and not necessarily strictly navigation, so it would be useful to have an explicit opt-in. Though if the fastest path to fixing this bug is to close on click for local navigation in the short term, I think there's low risk in doing that, given the limited support for other actions that would take place in the sidebar.
* I don't think sidebar open/close status is important to preserve in local navigation (and would be frustrating to have to navigate back multiple times just to have the sidebar open and close), though I'd be curious to hear a use-case where this would be useful. If someone wants to open/close the sidebar, they can just click on the page's open/close toggle anyway, but there's only one way for them to go back in history, and I wouldn't want to clutter that up.

Would be good to loop in Abby — getting her GitHub username to paste in here :)

**Comment by mkhatib** [comment]
@camelburrito what was the reasoning behind adding the open/close sidebar status to history?

**Comment by ericlindley-g** [comment]
cc/ @abeck000

**Comment by camelburrito** [comment]
When sidebar has an external link it would be good to maintain state when we navigate is back and forth

**Comment by dvoytenko** [comment]
@mkhatib

> Another reason I don't like popping open on close is this: open > close what does hitting back now do? My understanding it should re-open the sidebar - but in the case we have already popped open, this might do something completely different. No?

I'd say that re-opening sidebar on back button is definitely NOT an expected behavior. Just as is the case with native apps when you close sidebar on tap, clicking on back button doesn't reopen it. A tap or back button are just two ways for a user to close sidebar.

Generally, the goal is to always keep history stack shallow. Normally a user cannot remember how far back they can click and what they'd get. Also, opening a sidebar is a very simple gesture.

I could see how a `close-on-navigation` attribute, if set on a link, would explain whether the sidebar will be closed or not. But I don't see this as a default behavior. On most mobile devices the screen is too small to see any results of clicking on a link with the sidebar open. Instead, the right behavior is by default to always close the sidebar. Thus, I believe in most of cases, `close-on-navigation` is not helpful. 

The one nuance here that we could support directly is what if the target of the navigation is an element inside the sidebar. I believe the best solution here is to determine this fact and if the case, to NOT close the sidebar and due navigation with it open.

**Comment by mkhatib** [comment]
Alright, so been experimenting with closing the sidebar before handling the internal-link navigation. 

However I believe due to event queue the pushing of the new state (the internal link navigation) is happening before popping the previous state (the open sidebar) and hence when that state is popped it also pops the newly pushed state. 

I [played around with this and got it working with a sample code](https://github.com/ampproject/amphtml/pull/5520) by pushing the state by a delayed time. This is might not be the way we want to move forward with this, but this works. Now I need to go back and either figure out a nicer solution or clean this up if we think this is a good enough solution.

@dvoytenko if you have tips on how to better handle popping the state just before pushing a new one let me know.

**Comment by dvoytenko** [comment]
@mkhatib I didn't understand the issue with event sequencing. Let's continue that thread on the PR.

**Comment by mkhatib** [comment]
This should be fixed in the next release! 💃 💃 💃 💃 💃

**Comment by derat** [comment]
Per https://github.com/ampproject/amphtml/releases, commit #5961 was included in release 1480630085241. I still see this issue on https://www.erat.org/recipes.amp.html using release 1480633190770 and Chrome 54.0.2840.101, though. When I open the sidebar and click a link to e.g. https://www.erat.org/recipes.amp.html#cheesecake, the location bar is updated and the page scrolls to the proper location, but when I click on the page to dismiss the sidebar, Chrome navigates back to https://www.erat.org/recipes.amp.html and returns to the top of the page.

**Comment by mkhatib** [comment]
Hey @derat, that version should be in canary but that might have been reverted. I am unable to opt-in Canary. Both Canray and Prod seems to be serving the same prod version `1480633190770`. 

This might be due to a rollback in `canary` but yes that change has not yet made it into production. We'll investigate why canary has not been updated and try to push a new one on Monday.

cc/ @erwinmombay who might know why both prod and canary are serving same version `1480633190770` or if I am missing something.
