### ISSUE TITLE
validator errors

### ISSUE THREAD

**Issue by alxlu** [ampproject/amphtml#639]
When I use the snippet from the [Tutorial](https://github.com/ampproject/amphtml/blob/master/docs/create_page.md#write-the-basic-amp-html-page) and add "#development=1" to the end of the URL, I get the following errors:

```
Powered by AMP ⚡ HTML – Version 1444082436762
validator.js:159 AMP validation had errors:od.error @ validator.js:159(anonymous function) @ validator.js:174e.$ @ validator.js:96Xb @ validator.js:99y.vb @ validator.js:99Mb @ validator.js:94a @ es6.promise.js:89(anonymous function) @ es6.promise.js:100h @ $.microtask.js:17
validator.js:159 http://localhost:8080/#development=1:7:4 INVALID_ATTR_VALUE content=width=device-width,minimum-scale=1,initial-scale=1 (see https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#vprt)od.error @ validator.js:159(anonymous function) @ validator.js:174e.$ @ validator.js:96Xb @ validator.js:99y.vb @ validator.js:99Mb @ validator.js:94a @ es6.promise.js:89(anonymous function) @ es6.promise.js:100h @ $.microtask.js:17
validator.js:159 http://localhost:8080/#development=1:23:27 MANDATORY_TAG_MISSING viewport declaration (see https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#vprt)
```

I've also tried using the following sample on the README and it essentially returns the same error:
```HTML
<!doctype html>
<html ⚡>
  <head>
    <meta charset="utf-8">
    <link rel="canonical" href="hello-world.html" >
    <meta name="viewport" content="width=device-width,minimum-scale=1,initial-scale=1">
    <style>body {opacity: 0}</style><noscript><style>body {opacity: 1}</style></noscript>
    <script async src="https://cdn.ampproject.org/v0.js"></script>
  </head>
  <body>Hello World!</body>
</html>
```

Using the meta tag from https://www.ampproject.org/how-it-works also seems to throw basically the same error. But when I visit https://www.ampproject.org/how-it-works/#development=1, the meta tag error isn't there. However, it throws a different error:
```
Powered by AMP ⚡ HTML – Version 1444082436762
validator.js:159 AMP validation had errors:od.error @ validator.js:159(anonymous function) @ validator.js:174e.$ @ validator.js:96Xb @ validator.js:99y.vb @ validator.js:99Mb @ validator.js:94a @ es6.promise.js:89(anonymous function) @ es6.promise.js:100h @ $.microtask.js:17
validator.js:159 https://www.ampproject.org/how-it-works/#development=1:317:7 MANDATORY_TAG_MISSING html ⚡ for top-level html (see https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#ampd)
```
Are these expected? Or am I missing a step somewhere?

**Comment by erwinmombay** [comment]
`validator.js:159 http://localhost:8080/#development=1:7:4 INVALID_ATTR_VALUE content=width=device-width,minimum-scale=1,initial-scale=1 (see https://github.com/ampproject/amphtml/blob/master/spec/amp-html-format.md#vprt)od.error @ validator.js:159(anonymous function) @ validator.js:174e.$ @ validator.js:96Xb @ validator.js:99y.vb @ validator.js:99Mb @ validator.js:94a @ es6.promise.js:89(anonymous function) @ es6.promise.js:100h @ $.microtask.js:17`

should be resolved soon, this is more or less our spec being out of sync with the actual validator. (/cc @dvoytenko)

the latter `MANDATORY_TAG_MISSING html ⚡ for top-level html` is a little weirder. Can you take a look at your dom and make sure ⚡is there? if not can you try `<html amp>` instead?

<img width="446" alt="screen shot 2015-10-15 at 2 33 42 pm" src="https://cloud.githubusercontent.com/assets/354746/10528226/db858034-7349-11e5-86c6-b1cb2ca83a8e.png">

**Comment by amphtml-team** [comment]
Yes. That's correct. I made a note in the
https://github.com/ampproject/amphtml/issues/481 that validator is a bit
behind. I will send a note when it catches up.

**Comment by erwinmombay** [comment]
https://github.com/ampproject/amphtml/pull/640 should fix the first issue.

**Comment by dvoytenko** [comment]
No. That will only fix the example tests. People will still see errors in devmode on those documents, unfortunately.

**Comment by alxlu** [comment]
Ah, that makes sense. Thanks for the response!

The latter error is from the https://www.ampproject.org/how-it-works/ page&mdash;I just added the "#development=1". It seems like the markup on that page looks like this:
```html
<html amp-version="1444082436762" style="padding-top: 0px;">
```
I was just confused because the second meta tag error didn't show when adding "#development=1" after the URL, but it showed up when I copied the meta tag from the page into a new document. Although I'm guessing it might have been the validator stopping on the first error.

**Comment by cramforce** [comment]
@alxlu See comment on top of that page in the source code :)

**Comment by Stormjack** [comment]
Presently I'm seeing the behavior that @alxlu reported as well.  In addition to the #development=1 approach, is there also an online validator that we can paste markup into to perform the validation? Thanks.

**Comment by dvoytenko** [comment]
Should be now fixed. Thanks for reporting!

**Comment by Stormjack** [comment]
Thanks Dima!


________________________________
